import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full w-full px-2 bg-slate-50"
      style={{ boxShadow: 'inset 0px 0px 80px rgba(125, 166, 232, 0.2)' }}>
      <body className="container mx-auto">
        {children}
      </body>
    </html>
  );
}