import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "@/components";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="min-h-screen flex flex-col">
      <body className="container mx-auto">
        {children}
      </body>
    </html>
  );
}